---
name: cd
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 8
          distribution: 'temurin'

      - name: next release version
        id: nextversion
        uses: jenkins-x-plugins/jx-release-version@v2.5.1

      - name: Set Version
        run: |
          mvn --no-transfer-progress versions:set -DnewVersion=${{ steps.nextversion.outputs.version }}

      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Jenkins

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.21.1
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          name: next
          tag: next
          version: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Interesting
        id: interesting
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: |
          set -euxo pipefail
          echo $GITHUB_EVENT_NAME
          if [ "${GITHUB_EVENT_NAME}" = "push" ]
          then
            INTERESTING_CATEGORIES='[ðŸ’¥ðŸš¨ðŸŽ‰ðŸ›âš ðŸš€ðŸ‘·]|:(boom|tada|construction_worker):'
            CATEGORIES=$(gh api /repos/$GITHUB_REPOSITORY/releases | jq -e -r '.[] | select(.draft == true and .name == "next") | .body')
            if echo "${CATEGORIES}" | egrep -q "${INTERESTING_CATEGORIES}"; then
              echo "Interesting release"
              echo "should_release=true" >> $GITHUB_OUTPUT
            else
              echo "Not interesting release"
              echo "should_release=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "should_release=true" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: jenkins-infra/jenkins-maven-cd-action@master
        if: steps.interesting.outputs.should_release == 'true'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
