---
name: cd
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: next release version
        id: nextversion
        uses: jenkins-x-plugins/jx-release-version@v2.2.5

      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Jenkins

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.15.0
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          name: next
          tag: next
          version: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Interesting
        id: interesting
        if: steps.wait-for-build.outputs.conclusion == 'success'
        runs: |
          set -euxo pipefail
          echo $GITHUB_EVENT_NAME
          # TODO should check if this is a merge to master here.
          INTERESTING_CATEGORIES='[üí•üö®üéâüêõ‚ö†üöÄüë∑]|:(boom|tada|construction_worker):'
          CATEGORIES=$(gh api /repos/$GITHUB_REPOSITORY/releases | jq -e -r '.[] | select(.draft == true and .name == "next") | .body')
          echo $CATEGORIES

          echo $CATEGORIES | egrep "$INTERESTING_CATEGORIES"
          # TODO set an output based on the result of the egrep.

      - name: Release
        uses: jenkins-infra/jenkins-maven-cd-action@master
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
