---
name: E2E Tests

on: [workflow_dispatch, pull_request]

jobs:
  test-and-build:
    name: Test+Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build
        run: mvn --no-transfer-progress verify

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: jenkinsci/tekton-client-plugin:latest

      - name: Install Kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up Helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.5.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Kind
        uses: helm/kind-action@v1.1.0
        with:
          cluster_name: tekton-client-plugin

      - name: Configuring and testing the Installation
        run: |
          kubectl cluster-info --context kind-tekton-client-plugin
          kubectl get nodes

      - name: Load image on the nodes of the cluster
        run: |
          kind load docker-image --name=tekton-client-plugin jenkinsci/tekton-client-plugin:latest

      - name: Install Jenkins
        run: |
          helm repo add jenkins https://charts.jenkins.io
          helm install --set 'controller.image=jenkinsci/tekton-client-plugin,controller.tag=latest,controller.installPlugins=false,controller.ingress.enabled=true,controller.imagePullPolicy=Never' jenkins jenkins/jenkins --wait

      - name: Install Tekton
        run: |
          kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

      - name: Debug Installation
        run: |
          kubectl get namespaces
          kubectl get all
          curl -L -o tkn.tar.gz https://github.com/tektoncd/cli/releases/download/v0.17.0/tkn_0.17.0_Linux_x86_64.tar.gz
          tar xvfz tkn.tar.gz
          ./tkn pipelinerun list
          curl -L -o jcli.tar.gz https://github.com/jenkins-zh/jenkins-cli/releases/latest/download/jcli-linux-amd64.tar.gz
          tar xvfz jcli.tar.gz
          ./jcli --help

